_target_: src.smart.model.smart_gail.EGO_GMM_GAIL

defaults:
  - ego_gmm

model_config:
  n_batch_wosac_metric: 1
  n_vis_batch: 1
  n_vis_scenario: 1
  n_vis_rollout: 1
  decoder:
    hidden_dim: 64
    num_heads: 4
    head_dim: 8
    num_map_layers: 1
    num_agent_layers: 1
    time_span: 5
