_target_: src.smart.model.smart_gail.SMART_GAIL

defaults:
  - smart

model_config:
  decoder:
    hidden_dim: 128
    num_heads: 4
    head_dim: 8
    num_map_layers: 1
    num_agent_layers: 1
    time_span: 5
