# https://wandb.ai
#
#wandb:
#  _target_: lightning.pytorch.loggers.wandb.WandbLogger
#  name: ${task_name}
#  save_dir: "${paths.output_dir}"
#  offline: False
#  id: null # pass correct id to resume experiment!
#  anonymous: null # enable anonymous logging
#  project: sim_agent
#  log_model: False # upload lightning ckpts
#  prefix: "" # a string to put at the beginning of metric keys
#  entity: u3006612
#  group: ""
#  tags: []
#  job_type: ""
#  resume: allow

tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: ./logs  # Set your desired logging directory
  name: ${task_name} # Experiment name
  version: ${paths.output_dir}  # Auto-increments the version